config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'about#show'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/sitemap.xml', to: 'sitemaps#index', as: :sitemap, defaults: { format: :xml }
  get '/sitemap-pages.xml', to: 'sitemaps#pages', as: :sitemap_pages, defaults: { format: :xml }
  get '/sitemap-articles.xml', to: 'sitemaps#articles', as: :sitemap_articles, defaults: { format: :xml }
  get '/sitemap-talks.xml', to: 'sitemaps#talks', as: :sitemap_talks, defaults: { format: :xml }
  get '/sitemap-tags.xml', to: 'sitemaps#tags', as: :sitemap_tags, defaults: { format: :xml }

  get 'login', to: 'login#new', as: :login
  post 'login', to: 'login#create'
  delete 'login', to: 'login#destroy'

  get 'search', to: 'search#index', as: :search
  get 'settings', to: 'settings#index', as: :settings

  resources :tags, only: :show, param: :name

  resources :talks

  resources :articles, only: %i[index new create] do
    collection do
      get :rss, to: 'articles#atom', defaults: { format: :atom }
      get :atom, defaults: { format: :atom }
      get :atom_style, defaults: { format: :xsl }
    end
  end

  resources :articles, param: :slug, path: '', only: %i[show edit update destroy] do
    scope module: :articles do
      resources :link_previews, only: :show
    end
  end
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationModel
  attr_accessor :term, :result_count

  after_initialize do
    self.result_count ||= 5
  end

  def results
    return [] if term.blank?

    {
      articles: articles.load_async,
      tags: tags.load_async
    }
  end

  def articles
    return Article.none if term.blank?

    scope = Article.published.order(published_at: :desc, title: :asc).limit(result_count)

    if term.starts_with?('#')
      scope.tagged_with(term.gsub(/^#/, ''))
    else
      scope.where('title ILIKE ?', "%#{term}%")
    end
  end

  def tags
    return Tag.none if term.blank? || term.starts_with?('#')

    Tag.normalize_value_for(:name, term)

    Tag
      .where('name ILIKE ?', "%#{term}%")
      .order(name: :asc)
      .limit(result_count)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action do
    request.session_options[:skip] = true
  end

  def index
    @search = Search.new(permitted_params)
  end

  private

  def permitted_params
    params.fetch(:search, {}).permit(:term)
  end
end

app/views/search/index.html.erb
<% content_for :head do %>
  <title>Search | Stanko K.R.</title>
  <%= noindex_meta_tag %>
<% end %>

<%= turbo_frame_tag :search do %>
  <div class="relative mt-5 mx-5">
    <div class="absolute -top-4 -right-4 h-8 z-20">
      <%= link_to root_path, class: "flex items-center justify-center w-8 h-8 bg-white rounded-full shadow transition-all scale-100 hover:scale-110", data: { action: "dialog#close" } do %>
        <%= close_icon(class: "w-4 h-4 text-gray-500") %>
      <% end %>
    </div>

    <div class="relative flex flex-col divide-y bg-neutral-100 rounded-lg z-10 shadow md:shadow-xl dark:bg-neutral-900 dark:border dark:border-neutral-500">
      <h1 class="sr-only">Search</h1>
      <div class="grow-0 relative p-2 dark:border-neutral-500">
        <%= form_for @search, url: search_path, method: :get, html: { class: "flex flex-row items-center gap-x-4" } do |search_form| %>
          <label class="cursor-pointer">
            <%= search_icon(class: "w-6 h-6 text-indigo-600 hover:text-indigo-800 dark:text-yellow-500 dark:hover:text-yellow-400") %>
            <%= search_form.submit "", class: "hidden" %>
            <span class="sr-only"><%= t(".search") %></span>
          </label>
          <%= search_form.search_field :term, placeholder: t(".search_placeholder"), autofocus: true, class: "w-full inline bg-transparent border-0 focus:ring-0 dark:text-white" %>
        <% end %>
      </div>

      <div class="grow p-2 dark:border-neutral-500">
        <% results = @search.results %>

        <% if results.empty? && @search.term.present? %>
          <div class="p-2 text-gray-500">
            <%= t(".no_results") %>
          </div>
        <% elsif results.empty? %>
          <div class="p-2 text-gray-500">
            <%= t(".prompt") %>
          </div>
        <% else %>
          <ul class="flex flex-col divide-y">

            <% if results[:articles].any? %>
              <% results[:articles].each do |result| %>
                <%= cache([result, :search_result]) do %>
                  <li class="group/result overflow-hidden p-1">
                    <div class="relative p-1 rounded group-hover/result:bg-neutral-200 dark:group-hover/result:bg-neutral-700">
                      <%= link_to "", result, class: "absolute inset-0" %>
                      <div class="font-semibold dark:text-white truncate">
                        <%= result.title %>
                      </div>
                      <div class="text-sm text-neutral-500 dark:group-hover/result:text-neutral-400">
                        <%= result.class %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            <% end %>

            <% if results[:tags].any? %>
              <li>
                <div class="relative p-2">
                  <div class="font-semibold dark:text-white">
                    <%= Tag.model_name.human(count: 5) %>
                  </div>
                </div>
                <div class="px-2 pb-2 flex flex-wrap gap-2">
                  <% results[:tags].each do |tag| %>
                    <%= tag_bubble(tag) %>
                  <% end %>
                </div>
              </li>
            <% end %>

          </ul>
        <% end %>

      </div>
    </div>
  </div>
<% end %>