config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'about#show'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/sitemap.xml', to: 'sitemaps#index', as: :sitemap, defaults: { format: :xml }
  get '/sitemap-pages.xml', to: 'sitemaps#pages', as: :sitemap_pages, defaults: { format: :xml }
  get '/sitemap-articles.xml', to: 'sitemaps#articles', as: :sitemap_articles, defaults: { format: :xml }
  get '/sitemap-talks.xml', to: 'sitemaps#talks', as: :sitemap_talks, defaults: { format: :xml }
  get '/sitemap-tags.xml', to: 'sitemaps#tags', as: :sitemap_tags, defaults: { format: :xml }

  get 'login', to: 'login#new', as: :login
  post 'login', to: 'login#create'
  delete 'login', to: 'login#destroy'

  get 'search', to: 'search#index', as: :search
  get 'settings', to: 'settings#index', as: :settings

  resources :tags, only: :show, param: :name

  resources :talks

  resources :articles, only: %i[index new create] do
    collection do
      get :rss, to: 'articles#atom', defaults: { format: :atom }
      get :atom, defaults: { format: :atom }
      get :atom_style, defaults: { format: :xsl }
    end
  end

  resources :articles, param: :slug, path: '', only: %i[show edit update destroy] do
    scope module: :articles do
      resources :link_previews, only: :show
    end
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include ActionView::Helpers::TextHelper
  include Taggable

  has_rich_text :content

  validates :title,
            presence: true
  validates :content,
            presence: true
  validates :slug,
            presence: true
  validates :slug_id,
            presence: true,
            uniqueness: true

  before_validation do
    self.slug = title.presence&.parameterize if slug.blank?
    generate_slug_id! if slug_id.blank?
  end

  scope(:published, lambda do
    where(published: true).where.not(published_at: (Time.current..))
  end)

  class << self
    def generate_slug_id(length: 12)
      SecureRandom.alphanumeric(length)
    end

    def from_slug(slug)
      from_slug!(slug)
    rescue ActiveRecord::RecordNotFound => _e
      nil
    end

    def from_slug!(slug)
      raise(ActiveRecord::RecordNotFound.new(nil, slug, self, :id)) if slug.blank?

      id = slug.scan(/^.*-([^-]+)$/).flatten.first.presence
      raise(ActiveRecord::RecordNotFound.new(nil, id, self, :id)) if id.blank?

      find_by!(slug_id: id)
    end
  end

  def to_param
    slug
  end

  def slug
    [
      super.presence || title.presence&.parameterize,
      slug_id.presence
    ].compact.join('-').presence
  end

  def published?
    published && published_at <= Time.current
  end

  def excerpt(length: 300)
    truncate(plain_text, length: length, separator: ' ')
  end

  def estimated_reading_time(words_per_minute: 225)
    [(word_count.to_f / words_per_minute).ceil, 1].max.to_i
  end

  def word_count
    plain_text.scan(/\w+/).flatten.count
  end

  def plain_text
    content.body.to_plain_text.gsub(/\[[^\]]*\]/, '')
  end

  def generate_slug_id!
    self.slug_id = self.class.generate_slug_id
  end

  def related_articles(limit: 5)
    return Article.none if tags.empty?

    Article
      .published
      .where.not(id: id)
      .joins(:taggings)
      .where(taggings: { tag_id: tags.pluck(:id) })
      .group(:id)
      .order(Arel.sql('COUNT(taggings.tag_id) DESC'), published_at: :desc)
      .limit(limit)
  end

  def previous_article
    Article
      .published
      .where(published_at: ...published_at)
      .order(published_at: :desc)
      .first
  end

  def next_article
    Article
      .published
      .where(published_at: (published_at + 1.second)..)
      .order(published_at: :asc)
      .first
  end

  def self.popular(limit: 5)
    published.order(published_at: :desc).limit(limit)
  end
end

app/models/article/content_decorator.rb
# frozen_string_literal: true

require 'nokogiri'
require 'redcarpet'
require 'redcarpet/render_strip'

class Article
  class ContentDecorator < ApplicationDecorator
    RENDERERS = {
      html: HtmlRenderer
    }.freeze
    MARKDOWN_CONFIG = {
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      superscript: true,
      underline: true,
      highlight: true,
      footnotes: true
    }.freeze
    AVERAGE_ADULT_WORDS_PER_MINUTE = 200
    MARKDOWN_ATTACHMENT_URLS_REGEX = /!\[[^\]]*\]\((.+)\)/.freeze
    MARKDOWN_LINK_URLS_REGEX = /\[[^\]]*\]\((.+)\)/.freeze

    attr_reader :article

    def self.markdown_renderer(format)
      return unless RENDERERS.key?(format)

      @markdown_renderer ||= {}
      @markdown_renderer[format] ||= Redcarpet::Markdown.new(
        RENDERERS[format],
        **MARKDOWN_CONFIG
      )
    end

    def initialize(content, article)
      @article = article
      super(content)
    end

    def to_html(raw: false)
      @html_content ||= Nokogiri::HTML(render_to(:html)).tap do |document|
        next if raw

        add_publication_date_to_html_document(document)
        change_attachemnt_urls_in_html_document(document)
        add_link_preview_attributes_to_html_document(document)
      end.to_s
    end

    def to_text
      @text_content ||= Nokogiri::HTML(to_html(raw: true)).text.strip
    end

    def to_s
      object.to_s
    end

    def word_count
      @word_count ||= to_text.split(/\s+/)
                             .select { |word| word.length > 1 }
                             .count
    end

    def reading_time
      (word_count / AVERAGE_ADULT_WORDS_PER_MINUTE).ceil.to_i
    end

    def render_to(format)
      self.class.markdown_renderer(format)&.render(object)
    end

    def attachment_urls
      object.scan(MARKDOWN_ATTACHMENT_URLS_REGEX).flatten
    end

    def link_urls
      object.scan(MARKDOWN_LINK_URLS_REGEX).flatten
    end

    def valid_link?(href, hmac)
      hmac == link_id(href)
    end

    private

    def add_publication_date_to_html_document(document)
      document.css('body').first.add_previous_sibling(
        '<time class="article__publishing_date" '\
              "datetime=\"#{article.published_at.iso8601}\">"\
          "#{article.published_at.strftime('%B %d, %Y')}"\
        '</time>'
      )
    end

    def change_attachemnt_urls_in_html_document(document)
      image_map = article.images.map { |i| [i.original_path, i] }.to_h

      document.css('img').each do |img|
        image = image_map[img['src']]
        img['src'] = image&.image_url || img['src']
        img['loading'] = :lazy
        img['srcset'] = image&.srcset&.join(', ')

        _figure = img.wrap('<figure></figure>').parent

        if img['alt']
          img.add_next_sibling("<figcaption>#{img['alt']}</figcaption>")
        end
      end
    end

    def add_link_preview_attributes_to_html_document(document)
      document.css('a').each do |link|
        link['tabindex'] = 0
        link['data-controller'] = 'link-preview'
        link['data-link-preview-id-value'] = link_id(link['href'])
        link['data-action'] = 'mouseover->link-preview#show  mouseout->link-preview#hide focus->link-preview#show  blur->link-preview#hide'
      end
    end

    def link_id(href)
      OpenSSL::HMAC.hexdigest('SHA256', md5_digest, href)
    end

    def md5_digest
      @md5_digest ||= Digest::MD5.hexdigest(object)
    end
  end
end

app/models/article/link_preview.rb
# frozen_string_literal: true

class Article
  class LinkPreview < ApplicationModel
    FETCHERS = [
      WikipediaFetcher,
      GenericFetcher
    ].freeze

    attr_accessor :id, :url

    kredis_datetime :updated_at, expires_in: 30.days
    kredis_string :image_url, expires_in: 30.days
    kredis_string :title, expires_in: 30.days
    kredis_string :description, expires_in: 30.days

    # Makes kredis methods behave like normal AR/AM attr accessors
    %i[updated_at image_url title description].each do |name|
      alias_method("kredis_#{name}", name)

      define_method(name) do
        public_send("kredis_#{name}").value
      end

      define_method("#{name}=") do |new_value|
        public_send("kredis_#{name}").value = new_value
      end
    end

    after_initialize do
      self.id ||= self.class.id_from_url(url.to_s)
    end

    validates :url,
              presence: true,
              url: { loopback: false }
    validates :title,
              presence: true,
              if: :fetched?

    class << self
      def for(url:, article:)
        return nil unless article.content.body.links.include?(url)

        new(
          id: id_from_url(url),
          url: url
        )
      end

      def id_from_url(url)
        Base64.urlsafe_encode64(url)
      end
    end

    def cache_key
      [self.class.name.underscore, id || :new].join('/')
    end

    def unfetched?
      !fetched?
    end

    def fetched?
      title.present? || updated_at.present? || image_url.present? || description.present?
    end

    def image?
      image_url.present?
    end

    def fetch!
      return self if invalid?

      fetcher&.fetch!(url)

      if fetcher.data
        self.updated_at = Time.now.utc
        self.title = fetcher.data[:title]
        self.description = fetcher.data[:description]
        self.image_url = fetcher.data[:image_url]
      end

      self
    end

    def fetcher
      @fetcher ||= FETCHERS.find { |fetcher| fetcher.resolves?(url) }&.new
    end
  end
end

app/models/article/link_preview/generic_fetcher.rb
# frozen_string_literal: true

require 'async'
require 'async/http/internet'
require 'async/http/body/pipe'

class Article
  class LinkPreview
    class GenericFetcher < ApplicationModel
      USER_AGENT = 'stanko.io/1.0.0 link_preview_bot/1.0.0'
      REQUEST_TIMEOUT = 3
      MAX_REDIRECT = 10

      attr_accessor :data

      def self.resolves?(_url)
        true
      end

      def fetch!(url)
        self.data ||= {}

        Sync do |task|
          internet = Async::HTTP::Internet.new
          fetch_from_url!(internet, task, preprocess_url(url))
        ensure
          internet.close
        end

        self
      end

      private

      def preprocess_url(url)
        url
      end

      def fetch_from_url!(internet, task, url)
        redirect_count = 0
        response = nil

        loop do
          return if redirect_count > MAX_REDIRECT
          return if url.blank?

          task.with_timeout(REQUEST_TIMEOUT) do
            response = internet.get(url, headers, nil)
          end

          return parse_from_response_body!(response) if success?(response)

          # An error occured if it's not a redirect, break iteration
          return unless redirect?(response)

          redirect_count += 1
          url = redirect_to(response)
          response.close
        end
      rescue Async::TimeoutError, SocketError, ArgumentError, OpenSSL::SSL::SSLError
        nil
      ensure
        response&.close
      end

      def headers
        @headers ||= build_headers
      end

      def build_headers
        [
          ['User-Agent', USER_AGENT],
          ['Accept', accept_header]
        ]
      end

      def accept_header
        'text/html'
      end

      def parse_from_response_body!(response)
        pipe = Async::HTTP::Body::Pipe.new(response.body)

        parse_body(pipe.to_io)
      ensure
        pipe.close
      end

      def parse_body(io)
        Nokogiri::HTML::SAX::Parser
          .new(TagsSaxParser.new(data))
          .parse_io(io)
      end

      def success?(response)
        (200...300).include?(response.status)
      end

      def redirect?(response)
        (300...400).include?(response.status)
      end

      def redirect_to(response)
        response.headers['location']
      end
    end
  end
end

app/models/article/link_preview/wikipedia_fetcher.rb
# frozen_string_literal: true

class Article
  class LinkPreview
    class WikipediaFetcher < GenericFetcher
      WIKIPEDIA_LINK_REGEX = %r{^(.*\.)?wikipedia\.org(/.*)?$}i

      def self.resolves?(url)
        url&.match?(WIKIPEDIA_LINK_REGEX)
      end

      private

      def preprocess_url(url)
        uri = URI(url)

        article_id = uri.path.gsub(%r{^/wiki/}, '')
        uri.path = "/api/rest_v1/page/summary/#{article_id}"

        uri.to_s
      end

      def accept_header
        'application/json; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/Summary/1.2.0"'
      end

      def parse_body(io)
        response = JSON.parse(io.read)

        data[:title] ||= response.dig('titles', 'canonical')
        data[:image_url] ||= response.dig('thumbnail', 'source')
        data[:description] ||= response['extract']
      end
    end
  end
end

app/controllers/articles/link_previews_controller.rb
# frozen_string_literal: true

module Articles
  class LinkPreviewsController < ApplicationController
    layout false

    helper_method :url

    def show
      @article = Article.from_slug!(params[:article_slug])
      @link_preview = Article::LinkPreview.for(url: url, article: @article)

      return head :not_found if @link_preview.blank?
      return head :ok if request.head?

      @link_preview.fetch! unless @link_preview.fetched?

      fresh_when(@link_preview)
    end

    def url
      return if params[:id].blank?

      begin
        Base64.urlsafe_decode64(params[:id]).presence
      rescue ArgumentError
        nil
      end
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  ORDER = { published_at: :desc, id: :desc }.freeze
  RATIOS = [12, 25, 50].freeze

  before_action only: %i[index show atom] do
    request.session_options[:skip] = true
  end

  before_action only: %i[show edit update destroy] do
    @article = Article.from_slug!(params[:slug])
  rescue ActiveRecord::RecordNotFound
    raise if Rails.env.local?

    redirect_to({ controller: :errors, action: :not_found }, status: :see_other)
  end

  before_action only: %i[new create edit update destroy] do
    unauthorized if Current.user.blank?
  end

  def index
    articles = if Current.user.present?
                 scope
               else
                 scope.published
               end

    set_page_and_extract_portion_from(articles, per_page: RATIOS)

    @articles = @page.records

    fresh_when(@articles)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def atom
    request.format = :atom

    @articles = scope.published.order(ORDER)

    return unless params[:tag].present?

    @articles = @articles.tagged_with(params[:tag]&.split(','))
  end

  def atom_style
    request.format = :xsl

    @tags = Tag.order(:name)

    fresh_when(@tags)
  end

  def show
    @related_articles = @article.related_articles(limit: 5)
    @previous_article = @article.previous_article
    @next_article = @article.next_article
    @popular_articles = Article.popular(limit: 5).where.not(id: @article.id)

    fresh_when etag: [ @article, @related_articles, @previous_article, @next_article, @popular_articles ]
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permitted_params)

    if @article.save
      redirect_to({ action: :show, slug: @article.slug }, status: :see_other)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update(permitted_params)
      redirect_to({ action: :show, slug: @article.slug }, status: :see_other)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy!

    redirect_to({ action: :index }, status: :see_other)
  end

  private

  def permitted_params
    params.require(:article).permit(:title, :content, :publish_at, :published,
                                    :slug, :tags)
  end

  def scope
    Article
      .all
      .order(ORDER)
      .with_rich_text_content_and_embeds
      .strict_loading
  end
end

app/helpers/article_helper.rb
# frozen_string_literal: true

module ArticleHelper
  def article_list(articles, **options)
    options[:class] ||= 'flex flex-col divide-y'

    content_tag(:ul, **options) do
      render(articles)
    end
  end
end

app/views/articles/_article.html.erb
<%# locals: (article:, article_counter: nil, article_iteration: nil) -%>

<%= cache article do %>
  <li class="flex flex-col gap-y-1 py-4 lg:py-6 px-2 md:px-0 relative group">

    <%= link_to "", article_path(article), class: "absolute inset-0" %>

    <div class="text-xs text-neutral-600 flex flex-row gap-x-4 dark:text-neutral-500">
      <%= time_tag article.published_at, t(".published", date: l(article.published_at.to_date)) %>
      <span><%= t(".reading_time", duration: article.estimated_reading_time) %></span>
    </div>

    <div class="font-semibold text-xl">
      <%= article.title %>
    </div>

    <div class="text-sm">
      <%= article.excerpt %>
    </div>

  </li>
<% end %>

app/views/articles/_form.html.erb
<%= form_for article, html: { class: "flex flex-col gap-y-4" } do |article_form| %>
  <%= validation_errors(article_form) if article_form.object.errors.any? %>

  <label>
    <%= article_form.object.class.human_attribute_name(:title) %>
    <%= article_form.text_field :title, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <label>
    <%= article_form.object.class.human_attribute_name(:tags) %>
    <%= article_form.text_field :tags, value: article_form.object.tags.pluck(:name).join(", "), class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <div class="flex flex-col md:flex-row gap-x-4 gap-y-4">
    <label class="grow">
      <%= article_form.object.class.human_attribute_name(:publish_at) %>
      <%= article_form.datetime_field :publish_at, class: "w-full rounded border border-neutral-300 dark:text-black" %>
    </label>

    <label class="flex flex-row gap-x-2 items-center pt-5">
      <%= article_form.check_box :published %>
      <%= article_form.object.class.human_attribute_name(:published) %>
    </label>
  </div>

  <%= rich_text_field(article_form, :content) %>

  <%= article_form.submit t(".save"), class: "rounded text-white p-2 w-full cursor-pointer bg-indigo-500 hover:bg-indigo-700 dark:bg-yellow-500 dark:text-yellow-900 dark:hover:bg-yellow-400" %>
<% end %>

app/views/articles/atom_style.xsl.erb
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>
          RSS Feed |
          <xsl:value-of select="/atom:feed/atom:title"/>
        </title>
        <meta charset="utf-8"/>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <%= stylesheet_link_tag "tailwind", media: :all, "data-turbo-track": "reload" %>
      </head>
      <body>
        <main class="sm:max-w-xl mx-auto">
          <dk-alert-box type="info">
            <strong>This is an RSS feed</strong>. Subscribe by copying
            the URL from the address bar into your newsreader.
          </dk-alert-box>
          <div class="py-7">
            <h1 class="flex items-center gap-2 text-xl">
              <%= rss_icon(class: "w-7 text-orange-500") %>
              RSS Feed
            </h1>
            <h2 class="mt-4 text-2xl font-extrabold">stanko.io</h2>
            <a class="text-sm underline">
              <xsl:attribute name="href">
                <xsl:value-of select="/atom:feed/atom:link[1]/@href"/>
              </xsl:attribute>
              Visit Website &#x2192;
            </a>
            <div class="mt-7">
              <p class="text-sm">
                Filter by tag:
              </p>
              <ul class="flex flex-wrap gap-4 mt-2 text-sm">
                <li class="underline"><%= link_to("Everything", atom_articles_path) %></li>
                <% @tags.each do |tag| %>
                  <li class="underline">
                    <%= link_to(tag.name.titleize, atom_articles_path(tag: tag.name)) %>
                  </li>
                <% end %>
              </ul>
            </div>

            <h2 class="mt-7 mb-3 text-xl font-bold">
              Articles
            </h2>

            <xsl:for-each select="/atom:feed/atom:entry">
              <div class="pb-7">
                <div class="text-gray-500 text-xs font-italic">
                  Published on
                  <xsl:value-of select="substring(atom:published, 0, 11)" />
                </div>

                <div class="font-bold">
                  <a class="underline">
                    <xsl:attribute name="href">
                      <xsl:value-of select="atom:link/@href"/>
                    </xsl:attribute>
                    <xsl:value-of select="atom:title"/>
                  </a>
                </div>

                <div class="text-xs"><xsl:value-of select="atom:summary"/></div>
              </div>
            </xsl:for-each>
          </div>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

app/views/articles/edit.html.erb
<article class="px-2 md:px-0 flex flex-col gap-y-4">
  <div class="flex flex-row gap-x-4">
    <span><%= link_to text_with_icon(:arrow_long_left, t(".back")), article_path(@article), class: "text-indigo-600 hover:text-indigo-800 dark:text-yellow-500 dark:hover:text-yellow-400" %></span>
  </div>

  <div>
    <%= render "form", article: @article %>
  </div>
</article>

app/views/articles/index.html.erb
<% content_for :head do %>
  <title>Articles | Stanko K.R.</title>
  <%= content_tag(:link, nil, rel: "canonical", href: articles_url) %>
  <% seo_meta_tags(
    title: "Articles",
    description: "Collection of articles about Ruby, Rails, and software development",
    url: articles_url
  ).each { |tag| concat tag } %>
<% end %>

<div data-controller="infinite-scroll">
  <section class="mb-4 px-2 md:px-0">
    <h1 class="text-4xl font-semibold">Articles</h1>
  </section>

  <% if Current.user.present? %>
    <div class="flex flex-row gap-x-4">
      <%= link_to t(".new"), new_article_path, class: primary_button_classes %>
    </div>
  <% end %>

  <section>
    <% if @articles.any? %>
      <%= article_list(@articles, id: "articles") %>
    <% else %>
      <p>No articles were found</p>
    <% end %>
  </section>

  <%= paginate page: @page %>
</div>

app/views/articles/index.turbo_stream.erb
<%= turbo_stream.append "articles" do %>
  <%= render @articles %>
<% end %>

<%= turbo_stream.replace "pagination" do %>
  <%= render "articles/paginaton_controls", page: @page %>
<% end %>

app/views/articles/new.html.erb
<article class="px-2 md:px-0 flex flex-col gap-y-4">
  <div class="flex flex-row gap-x-4">
    <span><%= link_to text_with_icon(:arrow_long_left, t(".back")), articles_path, class: "text-indigo-600 hover:text-indigo-800 dark:text-yellow-500 dark:hover:text-yellow-400" %></span>
  </div>

  <div>
    <%= render "form", article: @article %>
  </div>
</article>

app/views/articles/show.html.erb
<%= content_for :head do %>
  <%= cache [@article, :head] do %>
    <% title = [truncate(@article.title, length: 60), "Stanko K.R."].join(" | ") %>
    <% excerpt = @article.excerpt(length: 160) %>
    <title><%= title %></title>
    <%= content_tag(:meta, nil, name: "description", content: excerpt) %>
    <%= content_tag(:meta, nil, rel: "canonical", href: article_url(@article.slug)) %>
    <%= content_tag(:meta, nil, name: "twitter:card", content: "summary") %>
    <%= content_tag(:meta, nil, name: "twitter:creator", content: "@monorkin") %>
    <%= content_tag(:meta, nil, property: "og:title", content: title) %>
    <%= content_tag(:meta, nil, property: "og:description", content: excerpt) %>
    <%= content_tag(:meta, nil, property: "og:locale", content: "en_US") %>
    <%= content_tag(:meta, nil, property: "og:type", content: "article") %>
    <%= content_tag(:meta, nil, property: "og:url", content: article_url(@article.slug)) %>
    <% first_image = @article.content.body.attachments.compact.select { |attachment| attachment.respond_to?(:image?) }.find(&:image?) %>
    <% if first_image.present? %>
      <% image = first_image.representation(resize_to_fill: [512, 512], saver: { strip: true }) %>
      <%= content_tag(:meta, nil, property: "og:image", content: image.processed.url) %>
      <%= content_tag(:meta, nil, property: "og:image:width", content: 512) %>
      <%= content_tag(:meta, nil, property: "og:image:height", content: 512) %>
    <% else %>
      <%= content_tag(:meta, nil, property: "og:image", content: asset_url("portrait/medium.jpg")) %>
      <%= content_tag(:meta, nil, name: "twitter:image:alt", content: "Portrait of Stanko K.R.") %>
    <% end %>
  <% end %>
<% end %>

<article class="px-2 md:px-0">
  <div class="flex flex-row gap-x-4">
    <span><%= link_to text_with_icon(:arrow_long_left, t(".back")), articles_path, class: "text-indigo-600 hover:text-indigo-800 dark:text-yellow-500 dark:hover:text-yellow-400" %></span>
    <% if Current.user.present? %>
      <span class="font-semibold"><%= link_to t(".edit"), edit_article_path(@article) %></span>
      <span class="font-semibold"><%= button_to t(".delete"), article_path(@article), method: :delete, data: { turbo_confirm: t(".confirm_delete") } %></span>
    <% end %>
  </div>

  <%= cache @article do %>
    <div class="text-neutral-600 dark:text-neutral-500">
      <%= time_tag @article.published_at, t('.published_on', date: l(@article.published_at.to_date)) %>
    </div>

    <div>
      <h1 class="text-4xl font-semibold mt-4 mb-2">
        <%= @article.title %>
      </h1>

      <div class="relative">
        <div class="z-50 absolute top-0 bottom-0 right-0 w-4 bg-gradient-to-l from-neutral-50 dark:from-black"></div>
        <div class="z-20 absolute top-0 bottom-0 left-0 w-4 bg-gradient-to-r from-neutral-50 dark:from-black"></div>
        <div class="z-10 overflow-x-scroll overflow-y-hidden">
          <div class="inline-block mr-4">
            <div class="mb-1 pb-2 flex flex-row gap-x-2">
              <% @article.tags.order(name: :asc).each do |tag| %>
                <%= tag_bubble(tag, class: "first:z-40") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div data-controller="article">
      <%== transform_rich_text(@article.content) %>
    </div>
  <% end %>
</article>

<section class="flex flex-col my-4 gap-y-8">
  <%= render "articles/show/navigation", previous_article: @previous_article, next_article: @next_article %>
  <%= render "articles/show/stay_updated_prompt" %>
  <%= render "articles/show/related_articles", related_articles: @related_articles, popular_articles: @popular_articles %>
</section>