config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'about#show'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/sitemap.xml', to: 'sitemaps#index', as: :sitemap, defaults: { format: :xml }
  get '/sitemap-pages.xml', to: 'sitemaps#pages', as: :sitemap_pages, defaults: { format: :xml }
  get '/sitemap-articles.xml', to: 'sitemaps#articles', as: :sitemap_articles, defaults: { format: :xml }
  get '/sitemap-talks.xml', to: 'sitemaps#talks', as: :sitemap_talks, defaults: { format: :xml }
  get '/sitemap-tags.xml', to: 'sitemaps#tags', as: :sitemap_tags, defaults: { format: :xml }

  get 'login', to: 'login#new', as: :login
  post 'login', to: 'login#create'
  delete 'login', to: 'login#destroy'

  get 'search', to: 'search#index', as: :search
  get 'settings', to: 'settings#index', as: :settings

  resources :tags, only: :show, param: :name

  resources :talks

  resources :articles, only: %i[index new create] do
    collection do
      get :rss, to: 'articles#atom', defaults: { format: :atom }
      get :atom, defaults: { format: :atom }
      get :atom_style, defaults: { format: :xsl }
    end
  end

  resources :articles, param: :slug, path: '', only: %i[show edit update destroy] do
    scope module: :articles do
      resources :link_previews, only: :show
    end
  end
end

app/models/talk.rb
# frozen_string_literal: true

class Talk < ApplicationRecord
  include ActionView::Helpers::TextHelper

  has_one_attached :video

  has_rich_text :description

  validates :title,
            presence: true
  validates :event,
            presence: true
  validates :held_at,
            presence: true

  class << self
    def from_slug!(slug)
      id = slug&.scan(/^(.*-)?(\d+)$/)&.flatten&.last

      find_by!(id: id)
    end
  end

  def to_param
    [
      title.presence&.parameterize,
      event.presence&.parameterize,
      id
    ].join('-').presence
  end

  def excerpt(length: 300)
    return nil if description.blank?

    truncate(plain_text, length: length, separator: ' ')
  end

  def plain_text
    description.body.to_plain_text.gsub(/\[[^\]]*\]/, '')
  end
end

app/controllers/talks_controller.rb
# frozen_string_literal: true

class TalksController < ApplicationController
  ORDER = { held_at: :desc, title: :asc, event: :asc }.freeze
  RATIOS = [12, 25, 50].freeze

  before_action only: %i[index show] do
    request.session_options[:skip] = true
  end

  before_action only: %i[show edit update destroy] do
    @talk = Talk.from_slug!(params[:id])
  rescue ActiveRecord::RecordNotFound
    raise if Rails.env.local?

    redirect_to({ controller: :errors, action: :not_found }, status: :see_other)
  end

  before_action only: %i[new create edit update destroy] do
    unauthorized if Current.user.blank?
  end

  def index
    set_page_and_extract_portion_from(scope, per_page: RATIOS)

    @talks = @page.records

    fresh_when(@talks)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    fresh_when(@talk)
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(permitted_params)

    if @talk.save
      redirect_to({ action: :show, id: @talk }, status: :see_other)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @talk.update(permitted_params)
      redirect_to({ action: :show, id: @talk }, status: :see_other)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @talk.destroy!

    redirect_to({ action: :index }, status: :see_other)
  end

  private

  def permitted_params
    params.require(:talk).permit(:title, :event, :event_url,
                                 :video_mirror_url, :held_at, :video, :description)
  end

  def scope
    Talk.all.order(ORDER).with_rich_text_description_and_embeds.strict_loading
  end
end

app/helpers/talk_helper.rb
# frozen_string_literal: true

module TalkHelper
  def talk_video_embed(talk)
    content_tag(:div, class: 'flex flex-col gap-y-4') do
      video_url = talk.video_mirror_url.presence
      video_url = url_for(talk.video) if video_url.blank? && talk.video.attached?

      concat(video_embed_for(video_url, class: 'aspect-video rounded')) if video_url.present?

      concat(content_tag(:div, class: 'flex flex-col gap-y-4 md:flex-row md:gap-x-4') do
        options = {
          class: 'text-indigo-600 hover:text-indigo-800 dark:text-yellow-500 dark:hover:text-yellow-400',
          target: '_blank',
          rel: 'noopener noreferrer'
        }

        concat(link_to(t('.download_video'), url_for(talk.video), options)) if talk.video.attached?
        concat(link_to(t('.mirror'), talk.video_mirror_url, options)) if talk.video_mirror_url.present?
      end)
    end
  end
end

app/views/talks/_form.html.erb
<%= form_for talk, html: { class: "flex flex-col gap-y-4" } do |talk_form| %>
  <%= validation_errors(talk_form) if talk_form.object.errors.any? %>

  <label>
    <%= talk_form.object.class.human_attribute_name(:title) %>
    <%= talk_form.text_field :title, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <label>
    <%= talk_form.object.class.human_attribute_name(:event) %>
    <%= talk_form.text_field :event, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <label>
    <%= talk_form.object.class.human_attribute_name(:event_url) %>
    <%= talk_form.text_field :event_url, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <label>
    <%= talk_form.object.class.human_attribute_name(:video_mirror_url) %>
    <%= talk_form.text_field :video_mirror_url, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <label>
    <%= talk_form.object.class.human_attribute_name(:video) %>
    <%= talk_form.file_field :video, accept: %w[.mp4 .m4v .webm].join(","), class: "w-full rounded border border-neutral-300 dark:text-black p-2" %>
  </label>

  <label>
    <%= talk_form.object.class.human_attribute_name(:held_at) %>
    <%= talk_form.datetime_field :held_at, class: "w-full rounded border border-neutral-300 dark:text-black" %>
  </label>

  <%= talk_form.rich_text_area(:description) %>

  <%= talk_form.submit t(".save"), class: "rounded text-white p-2 w-full cursor-pointer bg-indigo-500 hover:bg-indigo-700 dark:bg-yellow-500 dark:text-yellow-900 dark:hover:bg-yellow-400" %>
<% end %>

app/views/talks/_talk.html.erb
<li class="group">
  <div class="p-2 rounded-lg group-hover:bg-neutral-100 dark:group-hover:bg-neutral-900">
    <div class="relative">

      <%= link_to "", talk, class: "z-40 absolute inset-0" %>

      <div class="z-30 ml-8 py-3 flex flex-col gap-y-2">
        <div class="font-semibold">
          <%= talk.title %>
        </div>

        <div class="text-sm text-neutral-500 dark:text-neutral-400">
          <div class="font-semibold">
            <%= talk.event %>
          </div>
          <div>
            <%= l(talk.held_at.to_date) %>
          </div>
        </div>
      </div>

      <div class="z-20 w-4 h-4 bg-indigo-500 ring-4 ring-neutral-50 rounded-full absolute left-1 top-4 group-hover:ring-neutral-100 dark:bg-yellow-500 dark:ring-black dark:group-hover:ring-neutral-900"></div>

      <div class="z-10 w-px bg-indigo-300 absolute left-3 -top-2 -bottom-2 group-last:h-6 group-last:bottom-auto group-first:top-6 group-last:group-first:h-0 dark:bg-yellow-300"></div>

    </div>
  </div>
</li>

app/views/talks/edit.html.erb
<div class="flex flex-col gap-y-6">
  <h1 class="text-2xl font-bold"><%= t(".title") %></h1>

  <%= render "form", talk: @talk %>
</div>

app/views/talks/index.html.erb
<% content_for :head do %>
  <title>Talks | Stanko K.R.</title>
  <%= content_tag(:link, nil, rel: "canonical", href: talks_url) %>
  <% seo_meta_tags(
    title: "Talks",
    description: "Conference talks and presentations about Ruby, Rails, and web development",
    url: talks_url
  ).each { |tag| concat tag } %>
<% end %>

<div class="flex flex-col gap-y-6" data-controller="infinite-scroll">
  <section class="mb-4 px-2 md:px-0">
    <h1 class="text-4xl font-semibold">Talks</h1>
  </section>

  <% if Current.user.present? %>
    <div class="flex flex-row gap-x-4 px-2 md:px-0">
      <%= link_to t(".new"), new_talk_path, class: primary_button_classes %>
    </div>
  <% end %>

  <ul class="flex flex-col" id="talks">
    <%= render @talks %>
  </ul>

  <%= paginate page: @page %>
</div>

app/views/talks/index.turbo_stream.erb
<%= turbo_stream.append "talks" do %>
  <%= render @talks %>
<% end %>

<%= turbo_stream.replace "pagination" do %>
  <%= paginate page: @page %>
<% end %>

app/views/talks/new.html.erb
<div class="flex flex-col gap-y-6">
  <h1 class="text-2xl font-bold"><%= t(".title") %></h1>

  <%= render "form", talk: @talk %>
</div>

app/views/talks/show.html.erb
<% content_for :head do %>
  <% title = truncate(@talk.title, length: 60) %>
  <% description = @talk.excerpt(length: 160) || "A talk about #{@talk.title} at #{@talk.event}" %>
  <title><%= title %> | Stanko K.R.</title>
  <% seo_meta_tags(
    title: title,
    description: description,
    type: "article",
    url: talk_url(@talk)
  ).each { |tag| concat tag } %>
<% end %>

<div class="flex flex-col gap-y-4 px-2 md:px-0">

  <div class="flex flex-col gap-y-4">
    <h1 class="text-2xl font-semibold">
      <%= @talk.title %>
    </h1>

    <div class="flex flex-col gap-y-1 text-neutral-500 dark:text-neutral-400">
      <h2 class="font-semibold">
        <%= link_to_if @talk.event_url.present?, @talk.event, @talk.event_url, target: :_blank %>
      </h2>
      <%= time_tag @talk.held_at, l(@talk.held_at.to_date) %>
    </div>
  </div>

  <% if @talk.description.present? %>
    <div>
      <%== transform_rich_text(@talk.description) %>
    </div>
  <% end %>

  <div>
    <%= talk_video_embed(@talk) %>
  </div>

  <% if Current.user.present? %>
    <div class="flex flex-row gap-x-4">
      <span class="font-semibold"><%= link_to t(".edit"), edit_talk_path(@talk) %></span>
      <span class="font-semibold"><%= button_to t(".delete"), talk_path(@talk), method: :delete, data: { turbo_confirm: t(".confirm_delete") } %></span>
    </div>
  <% end %>
</div>